/*
 *    Copyright 2023 CROZ d.o.o, the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *
 */

export const registryConfigurationMock = [
  {
    groupId: "Address",
    groupIdDisplayName: "Address registry",
    entityConfigurationList: [
      {
        classFullName: "net.croz.nrichdemobackend.registry.model.Address",
        name: "Address",
        displayName: "Address",
        groupId: "Address",
        readOnly: false,
        creatable: true,
        updateable: true,
        deletable: true,
        idClassPropertyNameList: [],
        propertyConfigurationList: [
          {
            name: "id",
            javascriptType: "number",
            originalType: "java.lang.Long",
            formLabel: "Id",
            columnHeader: "Id",
            editable: false,
            sortable: true,
            searchable: true,
            id: true,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "city",
            javascriptType: "string",
            originalType: "java.lang.String",
            formLabel: "City",
            columnHeader: "City",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "country",
            javascriptType: "object",
            originalType: "net.croz.nrichdemobackend.registry.model.Country",
            singularAssociationReferencedClass: "net.croz.nrichdemobackend.registry.model.Country",
            formLabel: "Country",
            columnHeader: "Country",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: true,
            decimal: false,
          },
          {
            name: "createdDate",
            javascriptType: "date",
            originalType: "java.time.Instant",
            formLabel: "Created date",
            columnHeader: "Created date",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "lastModifiedDate",
            javascriptType: "date",
            originalType: "java.time.Instant",
            formLabel: "Last modified date",
            columnHeader: "Last modified date",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "street",
            javascriptType: "string",
            originalType: "java.lang.String",
            formLabel: "Street",
            columnHeader: "Street",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "streetNumber",
            javascriptType: "number",
            originalType: "java.lang.Integer",
            formLabel: "Street number",
            columnHeader: "Street number",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
        ],
        embeddedIdPropertyConfigurationList: [],
        historyPropertyConfigurationList: [
          {
            name: "revisionNumber",
            javascriptType: "number",
            originalType: "java.lang.Integer",
            formLabel: "Revision number",
            columnHeader: "Revision number",
            editable: false,
            sortable: true,
            searchable: false,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "revisionTimestamp",
            javascriptType: "date",
            originalType: "java.util.Date",
            formLabel: "Revision timestamp",
            columnHeader: "Revision timestamp",
            editable: false,
            sortable: true,
            searchable: false,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "revisionType",
            javascriptType: "string",
            originalType: "java.lang.String",
            formLabel: "Revision type",
            columnHeader: "Revision type",
            editable: false,
            sortable: true,
            searchable: false,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
        ],
        identifierAssigned: false,
        historyAvailable: true,
        idClassIdentity: false,
        embeddedIdentity: false,
      },
      {
        classFullName: "net.croz.nrichdemobackend.registry.model.Country",
        name: "Country",
        displayName: "Country",
        groupId: "Address",
        readOnly: false,
        creatable: true,
        updateable: true,
        deletable: true,
        idClassPropertyNameList: [],
        propertyConfigurationList: [
          {
            name: "id",
            javascriptType: "number",
            originalType: "java.lang.Long",
            formLabel: "Id",
            columnHeader: "Id",
            editable: false,
            sortable: true,
            searchable: true,
            id: true,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "createdDate",
            javascriptType: "date",
            originalType: "java.time.Instant",
            formLabel: "Created date",
            columnHeader: "Created date",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "lastModifiedDate",
            javascriptType: "date",
            originalType: "java.time.Instant",
            formLabel: "Last modified date",
            columnHeader: "Last modified date",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "name",
            javascriptType: "string",
            originalType: "java.lang.String",
            formLabel: "Name",
            columnHeader: "Name",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
        ],
        embeddedIdPropertyConfigurationList: [],
        historyPropertyConfigurationList: [
          {
            name: "revisionNumber",
            javascriptType: "number",
            originalType: "java.lang.Integer",
            formLabel: "Revision number",
            columnHeader: "Revision number",
            editable: false,
            sortable: true,
            searchable: false,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "revisionTimestamp",
            javascriptType: "date",
            originalType: "java.util.Date",
            formLabel: "Revision timestamp",
            columnHeader: "Revision timestamp",
            editable: false,
            sortable: true,
            searchable: false,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "revisionType",
            javascriptType: "string",
            originalType: "java.lang.String",
            formLabel: "Revision type",
            columnHeader: "Revision type",
            editable: false,
            sortable: true,
            searchable: false,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
        ],
        identifierAssigned: false,
        historyAvailable: true,
        idClassIdentity: false,
        embeddedIdentity: false,
      },
    ],
  },
  {
    groupId: "Book",
    groupIdDisplayName: "Book registry",
    entityConfigurationList: [
      {
        classFullName: "net.croz.nrichdemobackend.registry.model.Author",
        name: "Author",
        displayName: "Author",
        groupId: "Book",
        readOnly: false,
        creatable: true,
        updateable: true,
        deletable: true,
        idClassPropertyNameList: [],
        propertyConfigurationList: [
          {
            name: "id",
            javascriptType: "number",
            originalType: "java.lang.Long",
            formLabel: "Id",
            columnHeader: "Id",
            editable: false,
            sortable: true,
            searchable: true,
            id: true,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "createdDate",
            javascriptType: "date",
            originalType: "java.time.Instant",
            formLabel: "Created date",
            columnHeader: "Created date",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "firstName",
            javascriptType: "string",
            originalType: "java.lang.String",
            formLabel: "First name",
            columnHeader: "First name",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "isForeign",
            javascriptType: "boolean",
            originalType: "java.lang.Boolean",
            formLabel: "Foreign?",
            columnHeader: "Foreign?",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "lastModifiedDate",
            javascriptType: "date",
            originalType: "java.time.Instant",
            formLabel: "Last modified date",
            columnHeader: "Last modified date",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "lastName",
            javascriptType: "string",
            originalType: "java.lang.String",
            formLabel: "Last name",
            columnHeader: "Last name",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "similarAuthor",
            javascriptType: "object",
            originalType: "net.croz.nrichdemobackend.registry.model.Author",
            singularAssociationReferencedClass: "net.croz.nrichdemobackend.registry.model.Author",
            formLabel: "Similar author",
            columnHeader: "Similar author",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: true,
            decimal: false,
          },
        ],
        embeddedIdPropertyConfigurationList: [],
        historyPropertyConfigurationList: [
          {
            name: "revisionNumber",
            javascriptType: "number",
            originalType: "java.lang.Integer",
            formLabel: "Revision number",
            columnHeader: "Revision number",
            editable: false,
            sortable: true,
            searchable: false,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "revisionTimestamp",
            javascriptType: "date",
            originalType: "java.util.Date",
            formLabel: "Revision timestamp",
            columnHeader: "Revision timestamp",
            editable: false,
            sortable: true,
            searchable: false,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "revisionType",
            javascriptType: "string",
            originalType: "java.lang.String",
            formLabel: "Revision type",
            columnHeader: "Revision type",
            editable: false,
            sortable: true,
            searchable: false,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
        ],
        identifierAssigned: false,
        historyAvailable: false,
        idClassIdentity: false,
        embeddedIdentity: false,
      },
      {
        classFullName: "net.croz.nrichdemobackend.registry.model.AuthorBook",
        name: "AuthorBook",
        displayName: "Author book",
        groupId: "Book",
        readOnly: false,
        creatable: true,
        updateable: true,
        deletable: true,
        idClassPropertyNameList: [],
        propertyConfigurationList: [
          {
            name: "id",
            javascriptType: "object",
            originalType: "net.croz.nrichdemobackend.registry.model.AuthorBookId",
            formLabel: "Id",
            columnHeader: "Id",
            editable: true,
            sortable: true,
            searchable: true,
            id: true,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "createdDate",
            javascriptType: "date",
            originalType: "java.time.Instant",
            formLabel: "Created date",
            columnHeader: "Created date",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "edition",
            javascriptType: "string",
            originalType: "java.lang.String",
            formLabel: "Edition",
            columnHeader: "Edition",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "editionNumber",
            javascriptType: "number",
            originalType: "java.lang.Integer",
            formLabel: "Edition number",
            columnHeader: "Edition number",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "lastModifiedDate",
            javascriptType: "date",
            originalType: "java.time.Instant",
            formLabel: "Last modified date",
            columnHeader: "Last modified date",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
        ],
        embeddedIdPropertyConfigurationList: [
          {
            name: "id.author",
            javascriptType: "object",
            originalType: "net.croz.nrichdemobackend.registry.model.Author",
            singularAssociationReferencedClass: "net.croz.nrichdemobackend.registry.model.Author",
            formLabel: "Id author",
            columnHeader: "Id author",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: true,
            decimal: false,
          },
          {
            name: "id.book",
            javascriptType: "object",
            originalType: "net.croz.nrichdemobackend.registry.model.Book",
            singularAssociationReferencedClass: "net.croz.nrichdemobackend.registry.model.Book",
            formLabel: "Id book",
            columnHeader: "Id book",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: true,
            decimal: false,
          },
        ],
        historyPropertyConfigurationList: [
          {
            name: "revisionNumber",
            javascriptType: "number",
            originalType: "java.lang.Integer",
            formLabel: "Revision number",
            columnHeader: "Revision number",
            editable: false,
            sortable: true,
            searchable: false,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "revisionTimestamp",
            javascriptType: "date",
            originalType: "java.util.Date",
            formLabel: "Revision timestamp",
            columnHeader: "Revision timestamp",
            editable: false,
            sortable: true,
            searchable: false,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "revisionType",
            javascriptType: "string",
            originalType: "java.lang.String",
            formLabel: "Revision type",
            columnHeader: "Revision type",
            editable: false,
            sortable: true,
            searchable: false,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
        ],
        identifierAssigned: true,
        historyAvailable: false,
        idClassIdentity: false,
        embeddedIdentity: true,
      },
      {
        classFullName: "net.croz.nrichdemobackend.registry.model.Book",
        name: "Book",
        displayName: "Book",
        groupId: "Book",
        readOnly: false,
        creatable: true,
        updateable: true,
        deletable: true,
        idClassPropertyNameList: [],
        propertyConfigurationList: [
          {
            name: "id",
            javascriptType: "number",
            originalType: "java.lang.Long",
            formLabel: "Id",
            columnHeader: "Id",
            editable: false,
            sortable: true,
            searchable: true,
            id: true,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "bookType",
            javascriptType: "object",
            originalType: "net.croz.nrichdemobackend.registry.model.BookType",
            singularAssociationReferencedClass: "net.croz.nrichdemobackend.registry.model.BookType",
            formLabel: "Book type",
            columnHeader: "Book type",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: true,
            decimal: false,
          },
          {
            name: "createdDate",
            javascriptType: "date",
            originalType: "java.time.Instant",
            formLabel: "Created date",
            columnHeader: "Created date",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "isbn",
            javascriptType: "string",
            originalType: "java.lang.String",
            formLabel: "Isbn",
            columnHeader: "Isbn",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "lastModifiedDate",
            javascriptType: "date",
            originalType: "java.time.Instant",
            formLabel: "Last modified date",
            columnHeader: "Last modified date",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "title",
            javascriptType: "string",
            originalType: "java.lang.String",
            formLabel: "Title",
            columnHeader: "Title",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
        ],
        embeddedIdPropertyConfigurationList: [],
        historyPropertyConfigurationList: [
          {
            name: "revisionNumber",
            javascriptType: "number",
            originalType: "java.lang.Integer",
            formLabel: "Revision number",
            columnHeader: "Revision number",
            editable: false,
            sortable: true,
            searchable: false,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "revisionTimestamp",
            javascriptType: "date",
            originalType: "java.util.Date",
            formLabel: "Revision timestamp",
            columnHeader: "Revision timestamp",
            editable: false,
            sortable: true,
            searchable: false,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "revisionType",
            javascriptType: "string",
            originalType: "java.lang.String",
            formLabel: "Revision type",
            columnHeader: "Revision type",
            editable: false,
            sortable: true,
            searchable: false,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
        ],
        identifierAssigned: false,
        historyAvailable: false,
        idClassIdentity: false,
        embeddedIdentity: false,
      },
      {
        classFullName: "net.croz.nrichdemobackend.registry.model.BookType",
        name: "BookType",
        displayName: "BookType",
        groupId: "Book",
        readOnly: false,
        creatable: true,
        updateable: true,
        deletable: true,
        idClassPropertyNameList: [],
        propertyConfigurationList: [
          {
            name: "id",
            javascriptType: "number",
            originalType: "java.lang.Long",
            formLabel: "Id",
            columnHeader: "Id",
            editable: false,
            sortable: true,
            searchable: true,
            id: true,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "createdDate",
            javascriptType: "date",
            originalType: "java.time.Instant",
            formLabel: "Created date",
            columnHeader: "Created date",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "lastModifiedDate",
            javascriptType: "date",
            originalType: "java.time.Instant",
            formLabel: "Last modified date",
            columnHeader: "Last modified date",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "name",
            javascriptType: "string",
            originalType: "java.lang.String",
            formLabel: "Name",
            columnHeader: "Name",
            editable: true,
            sortable: true,
            searchable: true,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
        ],
        embeddedIdPropertyConfigurationList: [],
        historyPropertyConfigurationList: [
          {
            name: "revisionNumber",
            javascriptType: "number",
            originalType: "java.lang.Integer",
            formLabel: "Revision number",
            columnHeader: "Revision number",
            editable: false,
            sortable: true,
            searchable: false,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "revisionTimestamp",
            javascriptType: "date",
            originalType: "java.util.Date",
            formLabel: "Revision timestamp",
            columnHeader: "Revision timestamp",
            editable: false,
            sortable: true,
            searchable: false,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
          {
            name: "revisionType",
            javascriptType: "string",
            originalType: "java.lang.String",
            formLabel: "Revision type",
            columnHeader: "Revision type",
            editable: false,
            sortable: true,
            searchable: false,
            id: false,
            singularAssociation: false,
            decimal: false,
          },
        ],
        identifierAssigned: false,
        historyAvailable: false,
        idClassIdentity: false,
        embeddedIdentity: false,
      },
    ],
  },
];

export const registryListMock = {
  content: [
    {
      createdDate: "2023-02-02T07:56:36.225794Z",
      lastModifiedDate: "2023-02-02T07:56:36.225794Z",
      id: 1,
      street: "Street: 0",
      streetNumber: 1,
      city: "City: 0",
      country: {
        createdDate: "2023-02-02T07:56:36.219794Z",
        lastModifiedDate: "2023-02-02T07:56:36.219794Z",
        id: 1,
        name: "Country: 0",
        new: false,
        class: "net.croz.nrichdemobackend.registry.model.Country",
      },
      new: false,
      class: "net.croz.nrichdemobackend.registry.model.Address",
    },
    {
      createdDate: "2023-02-02T07:56:36.227795Z",
      lastModifiedDate: "2023-02-02T07:56:36.227795Z",
      id: 2,
      street: "Street: 1",
      streetNumber: 2,
      city: "City: 1",
      country: {
        createdDate: "2023-02-02T07:56:36.219794Z",
        lastModifiedDate: "2023-02-02T07:56:36.219794Z",
        id: 1,
        name: "Country: 0",
        new: false,
        class: "net.croz.nrichdemobackend.registry.model.Country",
      },
      new: false,
      class: "net.croz.nrichdemobackend.registry.model.Address",
    },
    {
      createdDate: "2023-02-02T07:56:36.227795Z",
      lastModifiedDate: "2023-02-02T07:56:36.227795Z",
      id: 3,
      street: "Street: 2",
      streetNumber: 3,
      city: "City: 2",
      country: {
        createdDate: "2023-02-02T07:56:36.219794Z",
        lastModifiedDate: "2023-02-02T07:56:36.219794Z",
        id: 1,
        name: "Country: 0",
        new: false,
        class: "net.croz.nrichdemobackend.registry.model.Country",
      },
      new: false,
      class: "net.croz.nrichdemobackend.registry.model.Address",
    },
  ],
  pageable: {
    sort: {
      empty: false,
      sorted: true,
      unsorted: false,
    },
    offset: 0,
    pageNumber: 0,
    pageSize: 3,
    unpaged: false,
    paged: true,
  },
  last: false,
  totalPages: 5,
  totalElements: 15,
  number: 0,
  size: 3,
  sort: {
    empty: false,
    sorted: true,
    unsorted: false,
  },
  first: true,
  numberOfElements: 3,
  empty: false,
};

export const registryListBulkMock = {
  "net.croz.nrichdemobackend.registry.model.Country": {
    content: [
      {
        createdDate: "2023-02-02T07:56:36.219794Z",
        lastModifiedDate: "2023-02-02T07:56:36.219794Z",
        id: 1,
        name: "Country: 0",
        new: false,
        class: "net.croz.nrichdemobackend.registry.model.Country",
      },
      {
        createdDate: "2023-02-02T07:56:36.221794Z",
        lastModifiedDate: "2023-02-02T07:56:36.221794Z",
        id: 2,
        name: "Country: 1",
        new: false,
        class: "net.croz.nrichdemobackend.registry.model.Country",
      },
      {
        createdDate: "2023-02-02T07:56:36.221794Z",
        lastModifiedDate: "2023-02-02T07:56:36.221794Z",
        id: 3,
        name: "Country: 2",
        new: false,
        class: "net.croz.nrichdemobackend.registry.model.Country",
      },
      {
        createdDate: "2023-02-02T07:56:36.221794Z",
        lastModifiedDate: "2023-02-02T07:56:36.221794Z",
        id: 4,
        name: "Country: 3",
        new: false,
        class: "net.croz.nrichdemobackend.registry.model.Country",
      },
      {
        createdDate: "2023-02-02T07:56:36.221794Z",
        lastModifiedDate: "2023-02-02T07:56:36.221794Z",
        id: 5,
        name: "Country: 4",
        new: false,
        class: "net.croz.nrichdemobackend.registry.model.Country",
      },
    ],
    pageable: {
      sort: {
        empty: false,
        sorted: true,
        unsorted: false,
      },
      offset: 0,
      pageNumber: 0,
      pageSize: 5,
      unpaged: false,
      paged: true,
    },
    last: true,
    totalPages: 1,
    totalElements: 5,
    number: 0,
    size: 5,
    sort: {
      empty: false,
      sorted: true,
      unsorted: false,
    },
    first: true,
    numberOfElements: 5,
    empty: false,
  },
  "net.croz.nrichdemobackend.registry.model.Address": {
    content: [
      {
        createdDate: "2023-02-02T07:56:36.225794Z",
        lastModifiedDate: "2023-02-02T07:56:36.225794Z",
        id: 1,
        street: "Street: 0",
        streetNumber: 1,
        city: "City: 0",
        country: {
          createdDate: "2023-02-02T07:56:36.219794Z",
          lastModifiedDate: "2023-02-02T07:56:36.219794Z",
          id: 1,
          name: "Country: 0",
          new: false,
          class: "net.croz.nrichdemobackend.registry.model.Country",
        },
        new: false,
        class: "net.croz.nrichdemobackend.registry.model.Address",
      },
      {
        createdDate: "2023-02-02T07:56:36.227795Z",
        lastModifiedDate: "2023-02-02T07:56:36.227795Z",
        id: 2,
        street: "Street: 1",
        streetNumber: 2,
        city: "City: 1",
        country: {
          createdDate: "2023-02-02T07:56:36.219794Z",
          lastModifiedDate: "2023-02-02T07:56:36.219794Z",
          id: 1,
          name: "Country: 0",
          new: false,
          class: "net.croz.nrichdemobackend.registry.model.Country",
        },
        new: false,
        class: "net.croz.nrichdemobackend.registry.model.Address",
      },
      {
        createdDate: "2023-02-02T07:56:36.227795Z",
        lastModifiedDate: "2023-02-02T07:56:36.227795Z",
        id: 3,
        street: "Street: 2",
        streetNumber: 3,
        city: "City: 2",
        country: {
          createdDate: "2023-02-02T07:56:36.219794Z",
          lastModifiedDate: "2023-02-02T07:56:36.219794Z",
          id: 1,
          name: "Country: 0",
          new: false,
          class: "net.croz.nrichdemobackend.registry.model.Country",
        },
        new: false,
        class: "net.croz.nrichdemobackend.registry.model.Address",
      },
    ],
    pageable: {
      sort: {
        empty: false,
        sorted: true,
        unsorted: false,
      },
      offset: 0,
      pageNumber: 0,
      pageSize: 3,
      unpaged: false,
      paged: true,
    },
    last: false,
    totalPages: 5,
    totalElements: 15,
    number: 0,
    size: 3,
    sort: {
      empty: false,
      sorted: true,
      unsorted: false,
    },
    first: true,
    numberOfElements: 3,
    empty: false,
  },
};

export const registryCreateResultMock = {
  createdDate: "2023-02-02T13:01:48.270610300Z",
  lastModifiedDate: "2023-02-02T13:01:48.270610300Z",
  id: 16,
  street: "Street: 0",
  streetNumber: 1,
  city: "City: 0",
  country: {
    createdDate: "2023-02-02T07:56:36.219794Z",
    lastModifiedDate: "2023-02-02T07:56:36.219794Z",
    id: 1,
    name: "Country: 0",
    new: false,
    hibernateLazyInitializer: {},
  },
  new: false,
  class: "net.croz.nrichdemobackend.registry.model.Address",
};

export const registryUpdateResultMock = {
  lastModifiedDate: "2023-02-02T15:17:09.842002700Z",
  id: 16,
  street: "Street: 3",
  streetNumber: 4,
  city: "City: 2",
  country: {
    id: 1,
    new: true,
    class: "net.croz.nrichdemobackend.registry.model.Country",
  },
  new: true,
  class: "net.croz.nrichdemobackend.registry.model.Address",
};
