name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ lts/* ]

    runs-on: ${{ matrix.os }}
    name: OS ${{ matrix.os }} - Node ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build all modules
        run: yarn build

      - name: Lint files
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Generate HTML documentation from TSDoc
        if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
        run: yarn docs:generate

      - name: Publish generated documentation to GitHub Pages
        if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          clean: true
          single-commit: true

      - name: Publish test code coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/**/coverage-final.json
