name: Publish

on:
  release:
    types: [ created ]

jobs:
  build:
    strategy:
      matrix:
        node: [ lts/* ]
        os: [ ubuntu-latest ]
        registry-url: [ 'https://registry.npmjs.org' ]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - Node ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: ${{ matrix.registry-url }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build all modules
        run: yarn build all

      - name: Publish to NPM registry
        run: yarn workspaces foreach --no-private --exclude demo npm publish --tolerate-republish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
